name: Documentation Checks
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  file-Check:
    runs-on: ubuntu-latest
    steps:
#      - name: Field Check
       - run: |
           cd ${{ github.workspace }}
           ls -la
#      - sudo bash ${{ github.workspace }}/test/test.sh

#  terraform-validate:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: import
#        run: |
#          echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
#      - uses: actions/setup-go@v2
#        with:
#          go-version: ${{ env.GO_VERSION }}
#      - name: terraform-validate
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin
#          go get -t github.com/katbyte/terrafmt
#          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
#          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
#          echo ${FILES}
#          ./scripts/terraform-validate.sh "${FILES[@]}"
#          if [[ "$?" == "1" ]]; then
#            echo "Please Check the Terraform Grammer" && exit 1
#          fi


