name: Documentation Checks
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  Field-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Field Check
        run: |

          if [ ! -d "${{ github.workspace }}/examples" ]; then
              RESULT="${RESULT} \n ---FAIL---\n: Please Add the EXAMPLES"
#              echo -e "\033[33m ${RESULT} \033[0m"
#              PostDingTalk "${RESULT}"
              exit 1
          fi

#      run: |
#          if [ ! -d "${{ github.workspace }}/examples/complete" ]; then
#              RESULT="${RESULT} \n ---FAIL---\n: Please Add the COMPLETE"
##              echo -e "\033[33m ${RESULT} \033[0m"
##              PostDingTalk "${RESULT}"
#              exit 1
#          fi
#
#      run: |
#          if [ ! -d "${{ github.workspace }}/examples/complete/tfvars" ]] ; then
#              RESULT="${RESULT} \n ---FAIL---\n: Please Add the TFVAR File"
##              echo -e "\033[33m ${RESULT} \033[0m"
##              PostDingTalk "${RESULT}"
#              exit 1
#          fi

#  terraform-validate:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: import
#        run: |
#          echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
#      - uses: actions/setup-go@v2
#        with:
#          go-version: ${{ env.GO_VERSION }}
#      - name: terraform-validate
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin
#          go get -t github.com/katbyte/terrafmt
#          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
#          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
#          echo ${FILES}
#          ./scripts/terraform-validate.sh "${FILES[@]}"
#          if [[ "$?" == "1" ]]; then
#            echo "Please Check the Terraform Grammer" && exit 1
#          fi


